version: '3.8'

services:
  # PostgreSQL service
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

  # Redis service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_net

  # Backend service (Django)
  backend:
    image: backend:latest
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - app_net

  # UI service
  ui:
    image: ui:latest
    ports:
      - "${UI_PORT}:${UI_PORT}"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net:
    driver: bridge
